### ISSUE TITLE
[Suggestion]Add Config option to toggle Villager Trades

### ISSUE THREAD

**Issue by BioMasterZap** [Paulem79/SimpleOres-fabric#3]
Hello again. No issues this time, just a suggestion. While trying to resolve an issue with a different mod, I noticed that Villagers have trades for the Simple Ores gear. This could be a bit of an issue for me since I was thinking to "disable" Tin, but since I can only turn off the world gen and remove the recipes, I don't think there is a way I could remove it from Villager Trades.

Also, I was a tad concerned that trades for Mythril and Addy might be a bit too good given how I was thinking to rebalance them. And I still have no idea how they additional trades play with the experimental Villager Trade Rebalance I'm running...

So, could a config option be added to toggle all the Simple Ores Villager Trades? Given how difficult it can be to work with trades, this seems like the simplest way to give players a way to disable any trades they don't want.

**Comment by Paulem79** [comment]
Hello, thank you again for your "issue"

For sure I can make some trades toggleable, I'll do that

**Comment by Paulem79** [comment]
Well, I need to do a bit of changes on some classes, so it takes time, also, I don't know if the actual system I'm doing will be efficient, so it'll take time

**Comment by Paulem79** [comment]
Well, I wanted to add trade customization, but I won't because it's a bit hard for some cases

**Comment by Paulem79** [comment]
okay, I can't add customization, definitely

**Comment by Paulem79** [comment]
Well, it's available on modrinth, curseforge is not accessible yet
